name: aws_s3_upload
description: A simple, convenient package for uploading to S3.
version: 1.6.1
homepage: https://github.com/Serdnad/aws_s3_upload

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  amazon_cognito_identity_dart_2: ^3.8.1
  http: ^1.3.0
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
